import type { Church } from "./types";

/**
 * Seed data for the Archdiocese of Jakarta, sourced from the parish
 * directory spreadsheet. Currently limited to Central, South, and North
 * Jakarta. `history` is a placeholder pending the real copy per parish —
 * swapping it in is a change to this file and nothing else.
 */
export const churches: Church[] = [
  {
    slug: "katedral",
    name: { en: "The Church of Our Lady of the Assumption", id: "Gereja Santa Perawan Maria Diangkat ke Surga" },
    category: { en: "Cathedral", id: "Katedral" },
    parish: "Katedral",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    consecratedOn: "1901-04-21",
    history: {
      en: [
        "The history of Jakarta Cathedral, and indeed of the Archdiocese of Jakarta itself, is rooted in the political upheaval of early 19th-century Europe. The rise of Louis Bonaparte, Napoleon's brother, as King of Holland brought various changes to that country and its colonies, including in matters of religion. After two centuries of prohibition, the practice of the Catholic faith was once again permitted in the Dutch East Indies.",
        "On 8 May 1807, Pope Pius VII created the Apostolic Prefecture of the East Indies and sent two priests, Father Jacobus Nelissen and Father Lambertus Prinsen, who arrived in Batavia on 4 April 1808, marking the resumption of the Catholic mission there. The earliest congregation worshipped in a bamboo house at Buffelsveld (around today's Lapangan Banteng), before moving into a former Protestant chapel in Senen. After a major fire swept the area on 27 July 1826, that building was judged unfit for use. Through the intercession of Commissioner-General du Bus de Gisignies, the church acquired a plot of land along with the former residence of Governor-General de Kock, the site that would become the Jakarta Cathedral complex.",
        "The first church on that site, measuring 35 by 17 metres, was blessed on 6 November 1829 by Mgr. Lambertus Prinsen (by then Apostolic Prefect) under the name De Kerk van Onze Lieve Vrouwe ten Hemelopneming, the Church of Our Lady of the Assumption. On 1 May 1845, a Pontifical Mass was held there for the first time, formally establishing it as a cathedral.",
        "The building's condition gradually worsened, prompting renovations in 1859 and 1880 that included relocating the main tower, which had been straining the roof structure. Three days after Easter in 1890, the roof suddenly collapsed, forcing the congregation to worship for nearly a decade in the bishop's former carriage-horse stable, repurposed as an \"Emergency Cathedral.\"",
        "Construction of the neo-Gothic building standing today began in 1891, to a design by Father Antonius Dijkmans, S.J., who was also an architect. Work stalled for lack of funds before resuming in 1899. Father C.W.J. Wenneker, S.J. blessed the first stone laid on the foundation, and engineer M.J. Hulswit carried the project through after Dijkmans returned to the Netherlands in 1894. On 21 April 1901, the new Jakarta Cathedral building was consecrated by the Vicar Apostolic of Batavia, Mgr. Edmundus Sybrandus Luypen, S.J., a Mass accompanied by the Saint Cecilia Choir, still active today.",
        "Over the past century, Jakarta Cathedral has borne witness to numerous milestones in Indonesian history. Between 1962 and 1965, Indonesian bishops took part in the Second Vatican Council, which brought many changes to Catholic religious life, alongside domestic political turmoil stemming from the fall of President Sukarno and the establishment of the New Order regime. Five years later, on 3–4 December, Pope Paul VI visited the Cathedral before leading a grand Mass at Senayan Stadium (Gelora Bung Karno), marking the first time the supreme leader of the Catholic Church visited Indonesia. A similar event was repeated on 9–14 October 1989 with the visit of Pope John Paul II, and again on 3–6 September 2024 with the visit of Pope Francis. On Christmas Eve, 24 December 2000, the Cathedral area was one of the sites of a bomb explosion in a series of terrorist attacks by Jemaah Islamiyah targeting a number of churches across various cities in Indonesia.",
        "Its long history, from a bamboo house in Buffelsveld to the neo-Gothic tower that stands today, makes Jakarta Cathedral more than just a house of worship. Designated a national cultural heritage site since 1999, the church stands directly facing Istiqlal Mosque, the largest mosque in Southeast Asia. Their close proximity has become a symbol of hope for harmonious relations among people of different faiths in Indonesia.",
      ].join("\n\n"),
      id: [
        "Sejarah Katedral Jakarta, bahkan Keuskupan Agung Jakarta itu sendiri, berakar dari gejolak politik di Eropa pada awal abad ke-19. Naiknya Louis Bonaparte, adik Napoleon, sebagai Raja Belanda membawa berbagai perubahan bagi negara tersebut dan jajahannya, salah satunya perihal agama. Setelah dua abad dilarang, praktik iman Katolik pun diizinkan kembali di Hindia Belanda.",
        "Pada 8 Mei 1807, Paus Pius VII menciptakan Prefektur Apostolik Hindia Timur, lalu mengutus dua imam, Pastor Jacobus Nelissen dan Pastor Lambertus Prinsen, ke Batavia. Keduanya tiba pada 4 April 1808, menandai dimulainya kembali misi Katolik di Hindia Belanda. Umat mula-mula beribadah di rumah bambu di Buffelsveld (sekitar Lapangan Banteng), sebelum pindah ke bekas kapel Protestan di Senen. Setelah kebakaran besar melanda kawasan tersebut pada 27 Juli 1826, bangunan itu dinilai tidak layak lagi digunakan. Lewat perantaraan Komisaris Jenderal du Bus de Gisignies, pihak gereja pun memperoleh sebidang tanah beserta bekas kediaman Gubernur Jenderal de Kock. Kawasan inilah yang menjadi cikal bakal kompleks Katedral Jakarta.",
        "Gedung gereja pertama di lokasi tersebut, berukuran 35 x 17 meter persegi, diberkati pada 6 November 1829 oleh Mgr. Lambertus Prinsen (kini Prefek Apostolik) dengan nama De Kerk van Onze Lieve Vrouwe ten Hemelopneming (Gereja Santa Perawan Maria Diangkat ke Surga). Pada 1 Mei 1845, Misa Pontifikal pun dilaksanakan untuk pertama kalinya di sana, sekaligus menetapkannya sebagai gereja katedral.",
        "Seiring berjalannya waktu, kondisi bangunan perlahan memburuk, mendorong terjadinya upaya-upaya renovasi pada 1859 dan 1880 yang meliputi pemindahan menara utama yang dinilai membebani struktur atap. Tiga hari setelah Paskah tahun 1890, atap gereja pun tiba-tiba runtuh, memaksa umat beribadah di bekas kandang kuda kereta uskup yang dialihfungsikan menjadi \"Katedral Darurat\" selama hampir sepuluh tahun.",
        "Pembangunan gereja baru dengan arsitektur neo-Gotik seperti sekarang dimulai pada 1891, menggunakan desain Pastor Antonius Dijkmans, S.J., yang juga seorang arsitek. Pembangunan sempat mangkrak akibat keterbatasan dana, sebelum dilanjutkan kembali pada 1899. Pemberkatan batu pertama di atas pondasi dilakukan oleh Pastor C.W.J. Wenneker, S.J., sementara pelaksanaannya dilanjutkan oleh insinyur M.J. Hulswit setelah Dijkmans kembali ke Belanda pada 1894. Pada 21 April 1901, bangunan baru Katedral Jakarta pun ditahbiskan oleh Vikaris Apostolik Batavia, Mgr. Edmundus Sybrandus Luypen, S.J. Misa kala itu diiringi oleh Paduan Suara Santa Cecilia, yang masih aktif hingga sekarang.",
        "Selama seabad belakangan, Katedral Jakarta menjadi saksi dari berbagai tonggak sejarah Indonesia. Pada tahun 1962-1965, para uskup Indonesia ikut serta dalam Konsili Vatikan II yang membawa banyak perubahan dalam kehidupan beragama umat Katolik. Kejadian tersebut juga dibarengi dengan gejolak politik dalam negeri akibat jatuhnya Presiden Soekarno dan berdirinya rezim Orde Baru. Lima tahun kemudian, pada 3-4 Desember, Paus Paulus VI mengunjungi Katedral sebelum memimpin misa akbar di Stadion Senayan (Gelora Bung Karno), menandai kali pertama pemimpin tertinggi Gereja Katolik mengunjungi Indonesia. Kejadian serupa terulang lagi pada 9-14 Oktober 1989 lewat kedatangan Paus Yohanes Paulus II, lalu 3-6 September 2024 lewat kunjungan Paus Fransiskus. Pada malam Natal 24 Desember 2000, kawasan Katedral menjadi salah satu lokasi ledakan bom dalam rangkaian serangan teroris Jemaah Islamiyah terhadap sejumlah gereja di berbagai kota di Indonesia.",
        "Sejarahnya yang panjang, dari rumah bambu di Buffelsveld hingga menara neo-Gotik yang berdiri sekarang, menjadikan Katedral Jakarta lebih dari sekadar bangunan ibadah. Gereja yang berstatus cagar budaya nasional sejak tahun 1999 ini berdiri berhadapan langsung dengan Masjid Istiqlal, masjid terbesar di Asia Tenggara. Kedekatan keduanya pun jadi simbol harapan bagi hubungan yang rukun antar umat beragama di Indonesia.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte TransJakarta Juanda", line: "Koridor 2", distanceM: 400 },
      { kind: "train", name: "Stasiun Juanda", distanceM: 500 },
    ],
    address: "Jalan Katedral No. 7B, Pasar Baru, Sawah Besar, Jakarta Pusat, DKI Jakarta",
    coords: [-6.169257, 106.833069],
  },
  {
    slug: "cempaka-putih",
    name: { en: "St. Paschal's Church", id: "Gereja Santo Paskalis" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Cempaka Putih Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    consecratedOn: "1987-06-17",
    history: {
      en: [
        "St. Paschal's began not as a parish but as a mission outpost of Kramat Parish, its earliest Masses held in a Dutch military canteen on Jalan Petruk and led by Fr. Nicholas Joannes Cornelius Geise, O.F.M., who would later become Bishop of Bogor.",
        "The congregation soon outgrew that arrangement. In 1947 a chapel and rectory were built on Jalan Tanah Tinggi, giving rise to Tanah Tinggi Parish, and on that site the first St. Paschal's Church was completed in 1952 and blessed by Mgr. P. Willekens, S.J. A census at the time recorded some 1,200 parishioners across 250 families.",
        "By the late 1970s the church had become too small, a problem made worse when the widening of Jalan Letjen Suprapto ate into its grounds. The parish's solution was to buy a 4,260-square-meter former ice factory site in Cempaka Putih for 200 million rupiah, drawing on parish funds, a loan from the Archdiocese, another from the Paschal Foundation, and money raised by Fr. Michael Angkur, O.F.M. That plot is where the church still stands today.",
        "Permits took five years to secure, and it wasn't until December 1985 that Jakarta Governor Tjokropranolo signed off on the project. A 250-square-meter chapel and the Lourdes hall were finished over 1985 and 1986, and on 29 December 1986 Fr. Aegidius A. Ngarut, O.F.M. laid the cornerstone of the main church. The building was consecrated on 17 June 1987 in a Solemn Mass led by then-Archbishop of Jakarta Mgr. Leo Sukoto, S.J., a ceremony that also marked Tanah Tinggi Parish's transformation into Cempaka Putih Parish.",
        "That history came full circle on 19 May 2012, when the parish marked its sixtieth anniversary with a Thanksgiving Mass led by Mgr. Ignatius Suharyo, who would himself go on to become Archbishop of Jakarta.",
      ].join("\n\n"),
      id: [
        "Gereja Santo Paskalis memulai sejarahnya ketika masih menjadi stasi dari Paroki Kramat. Kala itu, misa mingguan dipimpin oleh Pastor Nicholas Joannes Cornelius Geise, O.F.M. (kelak menjadi Uskup Bogor), yang dilaksanakan di kantin militer Belanda di Jalan Petruk.",
        "Seiring bertambahnya jumlah umat, kebutuhan akan tempat ibadah yang lebih layak pun menjadi mendesak. Pada tahun 1947, didirikan kapel dan pastoran di kawasan Jalan Tanah Tinggi, menandai terbentuknya Paroki Tanah Tinggi. Di lokasi yang sama, dibangun pula bangunan pertama Gereja Santo Paskalis, yang selesai pada tahun 1952 dan diberkati oleh Mgr. P. Willekens, S.J. Sensus saat itu mencatat jumlah umat sebanyak 1.200 jiwa di bawah 250 kepala keluarga.",
        "Menjelang akhir 1970-an, daya tampung gereja sudah tidak mencukupi lagi, apalagi setelah menyempit akibat pelebaran Jalan Letjen Suprapto. Sebagai solusi, paroki membeli lahan bekas pabrik es di wilayah Cempaka Putih seluas 4.260 m² seharga Rp200 juta. Dana dihimpun dari kas paroki, pinjaman KAJ, pinjaman Yayasan Paskalis, serta hasil penggalangan dana Pastor Michael Angkur, O.F.M. Di atas lahan tersebut Gereja Santo Paskalis berdiri hingga kini.",
        "Setelah proses perizinan yang berlangsung selama lima tahun, SK Gubernur DKI Jakarta Tjokropranolo akhirnya terbit pada Desember 1985. Kapel baru seluas 250 m² beserta Gedung Serba Guna Lourdes pun rampung dibangun pada 1985–1986. Setahun kemudian, tepatnya 29 Desember 1986, peletakan batu pertama gedung gereja utama dilakukan oleh Pastor Aegidius A. Ngarut, O.F.M. Puncaknya, pada 17 Juni 1987, gedung Gereja Santo Paskalis Paroki Cempaka Putih yang baru resmi diresmikan melalui Misa Agung yang dipimpin oleh Uskup Agung Jakarta kala itu, Mgr. Leo Sukoto, S.J. Relokasi ini pun praktis mengubah Paroki Tanah Tinggi menjadi Paroki Cempaka Putih.",
        "Perjalanan panjang Paroki Santo Paskalis sejak awal berdirinya kemudian menjadi bagian integral dari sejarah pelayanan Gereja Katolik di wilayah Cempaka Putih, yang puncaknya dirayakan dalam Misa Syukur Perayaan 60 Tahun Paroki pada 19 Mei 2012, dipimpin oleh Mgr. Ignatius Suharyo, yang kelak menjadi Uskup Agung Jakarta.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte Pasar Cempaka Putih", line: "Koridor 2", distanceM: 250 },
    ],
    address: "Jalan Letjen Suprapto No. C1/23, RT.8/RW.3, Cempaka Putih Barat, Cempaka Putih, Jakarta Pusat, DKI Jakarta 10520",
    coords: [-6.171942, 106.864648],
  },
  {
    slug: "menteng",
    name: { en: "St. Theresa's Church", id: "Gereja Santa Theresia" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Menteng Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    group: ["menteng", "ekspatriat"],
    history: {
      en: [
        "St. Theresa's owes its existence to the growth of Menteng and Gondangdia after 1930, as Batavia's boundaries pushed outward to absorb them. Catholics settling there faced a long trek to Mass at the Cathedral, so from 1927 they made do with a borrowed classroom at St. Theresa's School.",
        "The Cathedral parish eventually found them a permanent home: a plot on Jalan Soendaweg, now Jalan Gereja Theresia. Dutch architect J. Th. van Oyen and the firm Fermont-Cuypers took on the design in 1933, giving the building a European style and, notably, no central pillars, so the altar would be visible from anywhere in the room.",
        "Work finished in 1934, and Fr. Antonius Theodorus van Hoof, S.J., then Pro-Vicar Apostolic of Batavia, inaugurated the church and said its first Mass. St. Theresa's thus became Batavia's third Catholic church, after the Cathedral and St. Joseph's in Matraman. Its governing board, the PGDP, was formed on 9 January 1936, formally establishing the parish as an independent community, and by 8 March 1949 it had grown enough to spin off Jalan Malang Parish from its southern half.",
        "The church earned provincial heritage status in DKI Jakarta in 2025. Alongside its Indonesian-language congregation, it also hosts the St. Peter Canisius International Parish, which serves foreign nationals with Mass in English.",
      ].join("\n\n"),
      id: [
        "Sejarah Gereja Santa Theresia berakar dari pengembangan kawasan Menteng dan Gondangdia yang dimulai pada 1930, seiring perluasan Batavia ke arah kedua kawasan tersebut. Umat Katolik yang tinggal di sana harus berjalan kaki cukup jauh untuk mengikuti misa di Gereja Katedral, sehingga sejak 1927 mereka memanfaatkan ruang kelas di Sekolah Santa Theresia sebagai tempat ibadah sementara.",
        "Menanggapi hal tersebut, pihak Katedral mencari lahan untuk mendirikan gereja baru bagi umat di kawasan itu, dan menemukan sebidang tanah di Jalan Soendaweg (kini Jalan Gereja Theresia). Pada 1933, arsitek Belanda J. Th. van Oyen bersama biro perancang Fermont-Cuypers ditunjuk merancang bangunannya, yang dibuat dengan gaya Eropa dan tanpa tiang penyangga di tengah agar altar dapat terlihat dari segala penjuru ruangan.",
        "Proyek pembangunan tersebut selesai pada 1934. Diresmikan oleh Pastor Antonius Theodorus van Hoof, S.J., Pro-Vikaris Apostolik Batavia saat itu, yang juga mempersembahkan misa perdana di sana, Santa Theresia pun menjadi gereja ketiga di wilayah Batavia, setelah Katedral Jakarta dan Gereja Santo Yoseph, Matraman. Pada 9 Januari 1936, didirikan Pengurus Gereja dan Dana Papa (PGDP) Santa Theresia, menandai berdirinya Paroki Santa Theresia sebagai komunitas mandiri. Sejalan dengan pertumbuhan jemaatnya, paroki ini kemudian dimekarkan lewat pembentukan Paroki Jalan Malang di bagian selatan Menteng, pada 8 Maret 1949.",
        "Sejak tahun 2025, Gereja Santa Theresia tercatat resmi sebagai cagar budaya tingkat Provinsi DKI Jakarta. Selain melayani umat berbahasa Indonesia, gereja ini juga menaungi Paroki Internasional Santo Petrus Kanisius bagi umat berkewarganegaraan asing, dengan Perayaan Ekaristi dalam bahasa Inggris.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte M.H. Thamrin", line: "Koridor 1", distanceM: 300 },
      { kind: "mrt", name: "Stasiun MRT Bundaran HI", distanceM: 450 },
      { kind: "train", name: "Stasiun Gondangdia", line: "Lin Bogor", distanceM: 850 },
    ],
    address: "Jalan Gereja Theresia No. 2, RT.8/RW.4, Gondangdia, Menteng, Jakarta Pusat, DKI Jakarta 10350",
    coords: [-6.188889, 106.825472],
  },
  {
    slug: "jalan-malang",
    name: { en: "St. Ignatius Loyola Church", id: "Gereja Santo Ignatius Loyola" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Jalan Malang Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    history: {
      en: [
        "Before it had a church of its own, this community worshipped under St. Theresa's Parish, gathering for weekly Mass in a private home at Jalan Malang No. 23. As the congregation grew past what that house could hold, parish priest Fr. J. van Niekerk, S.J. bought the property next door, No. 22, on 8 July 1948, after its Dutch owner sold up and left for the Netherlands.",
        "Leadership passed a month later to Fr. J. Awick, S.J., who carried on the work of expanding the facilities. The area became its own parish on 8 March 1949 under the patronage of St. Ignatius Loyola, a name that reflected the Jesuits' role in running it, even though the parish still had no permanent church building. It would be another sixteen years before that changed: Fr. Th. Liem Sik Hok, S.J. arrived as parish priest on 15 July 1965 and revived plans for a proper building, hiring local architect Bernard Yusuf to design one for the tight, awkwardly shaped corner lot available. A permit came through on 6 February 1967, and construction proceeded under the Archdiocese's supervision. Around the same time, the parish weighed buying a nearby house for the sisters to live in, a property that had once belonged to Njoto, a senior Indonesian Communist Party figure, and was, at that point, still occupied by soldiers.",
        "The finished church is unusual among Jakarta's parishes for its shape: a pyramid, a form almost never used in church architecture from that era. Pastoral responsibility has since passed from the Jesuits to diocesan priests of the Archdiocese.",
      ].join("\n\n"),
      id: [
        "Sebelum memiliki bangunannya sendiri, umat yang kini bernaung di Paroki Jalan Malang mulanya beribadah sebagai bagian dari Paroki Santa Theresia, dengan misa mingguan yang diadakan di rumah salah satu keluarga Katolik di Jalan Malang No. 23. Seiring bertambahnya umat, tempat tersebut tidak lagi memadai, sehingga Pastor Paroki J. van Niekerk, SJ, membeli rumah di Jalan Malang No. 22 pada 8 Juli 1948, setelah pemilik sebelumnya kembali ke Belanda.",
        "Sebulan kemudian, kepemimpinan Paroki Santa Theresia beralih ke Pastor J. Awick, S.J., yang melanjutkan upaya memperluas fasilitas ibadah. Wilayah ini kemudian ditetapkan sebagai paroki tersendiri pada 8 Maret 1949, dengan nama pelindung Santo Ignatius Loyola, refleksi dari kepengurusannya oleh Serikat Yesus (Yesuit), meski saat itu belum memiliki tempat ibadah tetap. Gagasan membangun gedung gereja pun baru diteruskan pada 15 Juli 1965, ketika Pastor Th. Liem Sik Hok, S.J., mulai menjabat sebagai pastor kepala. Bernard Yusuf, seorang arsitek sekaligus warga setempat, dipercaya merancang bangunan gereja di atas lahan yang relatif sempit dan berada di sudut jalan. Setelah Izin Mendirikan Bangunan diterbitkan pada 6 Februari 1967, pembangunan pun dilaksanakan di bawah pengawasan Keuskupan Agung Jakarta. Pada masa tersebut, paroki juga sempat berencana membeli sebuah rumah di belakang gereja untuk dijadikan tempat tinggal suster, yang sebelumnya pernah menjadi kediaman Njoto, salah seorang pimpinan PKI, dan saat itu masih ditempati oleh tentara.",
        "Gereja Santo Ignatius Loyola punya gaya arsitektur yang khas, berbentuk menyerupai limas atau piramida yang jarang dijumpai pada gereja-gereja yang dibangun dalam beberapa dekade terakhir. Belakangan, pelayanan pastoralnya sudah beralih dari Serikat Yesus ke para imam diosesan Keuskupan Agung Jakarta.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte Pasar Rumput", line: "Koridor 4", distanceM: 450 },
    ],
    address: "Jalan Malang No. 22, Menteng, Jakarta Pusat 10310",
    coords: [-6.205549, 106.839061],
  },
  {
    slug: "pejompongan",
    name: { en: "Christ the King Church", id: "Gereja Kristus Raja" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Pejompongan Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    consecratedOn: "2012-12-24",
    history: {
      en: [
        "The roots of this parish lie in Pejompongan and Bendungan Hilir's development as civil-servant housing in the early 1960s. Catholics who moved into the new neighborhood were initially under St. Theresa's Parish and had no fixed place to worship, rotating Mass between members' homes before settling for about five years in a hall borrowed from Dr. Mintohardjo Naval Hospital. Their community gained structure with the founding of the Pejompongan Catholic Family Association in 1960.",
        "A February 1964 letter secured land for the parish on Jalan Danau Toba through the Ministry of Public Works, with Ir. Bian Poen and Ir. F.X. Marsud overseeing construction. The building, made almost entirely of wood, was usable by Easter 1967 though not truly finished until 1970. The new parish took the name Christ the Savior and was placed under the care of the Congregation of the Immaculate Heart of Mary, with Fr. Clemens Scherus, C.I.C.M. as its first pastor. It initially included Slipi, which broke away as its own parish on 24 May 1972, after which Pejompongan renamed its church Christ the King, leaving Slipi to keep the name Christ the Savior.",
        "Decades later, in 2008, chronic flooding pushed the parish to consider rebuilding entirely. Ground wasn't broken until late 2010, and while construction was underway the congregation held services at GPIB Anugerah, a Protestant church roughly 350 meters away. The new building was completed in 2012 and debuted that same year at Christmas Eve Mass.",
        "Architect Ir. Josef W. Arga Setya gave the church its most distinctive feature: a roof that curves like a leaf, which has earned the building the nickname \"the Leaf Church.\" The theme continues inside, from a main cross carved directly into an eight-meter teak trunk by sculptor I Wayan Winten to ceramic flooring and Stations of the Cross by artist F.X. Widayanto.",
      ].join("\n\n"),
      id: [
        "Awal mula Paroki Pejompongan bermula sejak pengembangan wilayah Pejompongan, Bendungan Hilir sebagai hunian pegawai negeri pada awal 1960-an. Kala itu, umat Katolik yang tinggal di sana masih dinaungi oleh Paroki Santa Theresia dan sempat beribadah berpindah-pindah dari rumah ke rumah, sebelum akhirnya menumpang di aula Rumah Sakit Angkatan Laut dr. Mintohardjo selama kurang lebih lima tahun. Kegiatan umat kemudian semakin terorganisasi setelah berdirinya Ikatan Keluarga Katolik Pejompongan (IKKP) pada 1960.",
        "Lewat surat tertanggal 13 Februari 1964, Kementerian Pekerjaan Umum memperoleh sebidang tanah di Jalan Danau Toba untuk proyek pembangunan gereja yang ditangani oleh Ir. Bian Poen dan Ir. F.X. Marsud. Gedung mulai digunakan pada tahun 1967 untuk perayaan Paskah, meski proses penyempurnaan bangunan gereja tersebut, yang hampir seluruhnya terbuat dari kayu baru benar-benar selesai pada 1970. Paroki Pejompongan pun terbentuk, dengan nama pelindung Kristus Salvator di bawah pelayanan Kongregasi Hati Maria Tak Bernoda (CICM), dengan Pastor Clemens Scherus, C.I.C.M. sebagai pastor pertamanya. Saat itu, wilayah paroki masih mencakup Slipi, yang kemudian memekarkan diri pada 24 Mei 1972. Pasca pemekaran tersebut, Paroki Pejompongan mengganti nama gerejanya menjadi Kristus Raja, sementara Paroki Slipi mempertahankan nama Kristus Salvator.",
        "Babak baru bagi Paroki Pejompongan bermula ketika rencana pembangunan ulang gedung digulirkan pada 2008 untuk mengatasi banjir yang kerap melanda wilayah sekitarnya. Proyek tersebut pun baru dimulai pada akhir tahun 2010, dan selama prosesnya, umat Paroki Pejompongan menumpang beribadah di GPIB Anugerah yang berjarak sekitar 350 meter dari Gereja Kristus Raja. Konstruksi pun rampung pada 2012, dan gedung baru tersebut mulai digunakan secara resmi dalam perayaan Misa Malam Natal pada tahun yang sama.",
        "Gereja Kristus Raja yang berdiri sekarang dirancang oleh Ir. Josef W. Arga Setya dan memiliki arsitektur yang unik, dengan atap meliuk menyerupai daun, membuatnya dijuluki “Gereja Daun”. Ciri khas tersebut turut terasa pada objek-objek di dalamnya, misalnya salib utama yang diukir langsung pada sebatang pohon jati setinggi 8 meter oleh pematung I Wayan Winten, serta lantai keramik dan elemen-elemen Jalan Salib yang digarap oleh seniman keramik F.X. Widayanto.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte SDN Bendungan Hilir 01", line: "Non-BRT feeder", distanceM: 600 },
    ],
    address: "Jalan Danau Toba No. 56, RT.18/RW.4, Bendungan Hilir, Tanah Abang, Jakarta Pusat, DKI Jakarta 10210",
    coords: [-6.208202, 106.80903],
  },
  {
    slug: "kramat",
    name: { en: "Sacred Heart Church", id: "Gereja Hati Kudus" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Kramat Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    consecratedOn: "1920-07-02",
    history: {
      en: [
        "Kramat Parish grew out of an orphanage the St. Vincent de Paul Foundation, later the Vincentian Association of Jakarta, opened in the mid-19th century for Batavia's abandoned children. The children were first housed around Pasar Baru and Jalan Kwini before eventually relocating to Kramat, where a small chapel was built in the late 1800s as the seed of a future parish carved out of the Cathedral's territory. That parish became official on 2 July 1920, consecrated as Heilig Hart Kerk, Sacred Heart Church.",
        "Jesuits ran the parish early on and founded several Catholic schools in the surrounding area, including one now known as St. Joseph's School. Their stewardship ended in 1929, when the Franciscans took over following a 1927 request from Cardinal Willem Marinus van Rossum for Dutch Franciscans to assist the Jesuits on Java. After the order's leadership approved the move on 9 April 1929, five Dutch friars landed at Sunda Kelapa on 21 December that year to assume charge of both Kramat and Matraman parishes.",
        "The Japanese occupation during World War II brought parish activity to a halt, as many priests and religious were arrested or interned and the church itself had to close for a time, reopening only after the war ended. The building standing today dates to 1987, designed by Sr. Fendra, O.S.U. to replace the original 1920-21 structure.",
        "Sacred Heart is also known as a home for the Great Novena of St. Anthony of Padua, a devotion that began modestly, with a small weekly gathering every Tuesday, and grew substantially after Fr. Martinus Antonius Weselinus Brouwer began preaching on nine consecutive Tuesdays starting in 1950. The parish likewise holds a Great Novena for St. Francis of Assisi ahead of his 4 October feast day.",
        "Its complex on Jalan Kramat Raya No. 134 in Central Jakarta also houses Sint Joseph Elementary School and the Vincentius Putra Orphanage, both under the Vincentian Association of Jakarta. The parish's territory now covers four subdistricts, Senen, Johar Baru, Menteng, and Cempaka Putih, plus three satellite chapels: St. Vincent de Paul, St. Charles Borromeo at St. Carolus Hospital, and St. Peter Canisius at Kolese Kanisius.",
      ].join("\n\n"),
      id: [
        "Paroki Kramat bermula dari sebuah panti asuhan yang didirikan Yayasan Santo Vincentius a Paulo (kelak Perhimpunan Vincentius Jakarta) pada pertengahan abad ke-19 untuk menampung anak-anak terlantar di Batavia. Sebagian dari mereka mula-mula ditempatkan di Pasar Baru dan Jalan Kwini, sebelum akhirnya dipindahkan ke kawasan Kramat. Di kompleks itulah dibangun sebuah kapel kecil pada akhir abad ke-19, disiapkan sebagai calon paroki hasil pemekaran dari Paroki Katedral, hingga akhirnya diberkati dan resmi berdiri sebagai paroki pada 2 Juli 1920 dengan nama Heilig Hart Kerk (Gereja Hati Kudus).",
        "Pelayanan paroki saat itu dipegang oleh para imam Serikat Yesus (Yesuit), yang turut mendirikan sejumlah sekolah Katolik di sekitar Kramat, salah satunya kini dikenal sebagai Sekolah Santo Yosef. Peralihan pelayanan ke Ordo Fransiskan (OFM) terjadi pada 1929, bermula dari surat Kardinal Willem Marinus van Rossum pada 1927 yang meminta para Fransiskan Belanda membantu imam Yesuit di Pulau Jawa. Setelah dibahas dalam sidang dewan pimpinan Fransiskan pada 9 April 1929, lima biarawan Fransiskan asal Belanda tiba di Pelabuhan Sunda Kelapa pada 21 Desember 1929 untuk mengambil alih Paroki Kramat sekaligus Paroki Matraman.",
        "Masa pendudukan Jepang selama Perang Dunia II sempat melumpuhkan kegiatan paroki. Banyak imam dan biarawan ditangkap atau diinternir, membuat Gereja Kramat harus ditutup untuk beberapa waktu, sebelum kembali beraktivitas seusai perang. Gedung gereja yang berdiri sekarang sendiri baru dibangun pada 1987, menurut rancangan Sr. Fendra, O.S.U., menggantikan bangunan pertama yang telah berdiri sejak 1920-21.",
        "Gereja Hati Kudus juga dikenal sebagai salah satu pusat penyelenggaraan Novena Besar Santo Antonius Padua. Tradisi ini bermula dari salve mingguan setiap Selasa untuk menghormati Santo Antonius, yang mulanya hanya dihadiri sedikit umat. Devosi ini kian berkembang setelah Pastor Martinus Antonius Weselinus Brouwer, sejak 1950, aktif berkhotbah pada sembilan hari Selasa berturut-turut. Selain itu, paroki ini turut menggelar Novena Besar Santo Fransiskus Assisi menjelang peringatannya setiap 4 Oktober.",
        "Di dalam kompleks gereja, yang berlokasi di Jalan Kramat Raya No. 134, Jakarta Pusat, juga berdiri Sekolah Dasar Sint Joseph dan Panti Asuhan Vincentius Putra, keduanya di bawah pengelolaan Perhimpunan Vincentius Jakarta. Wilayah pelayanan Paroki Kramat sendiri kini membentang di empat kecamatan, Senen, Johar Baru, Menteng, dan Cempaka Putih, dengan tiga kapel tambahan: Kapel Santo Vincentius a Paulo, Kapel Santo Carolus Borromeus di RS Saint Carolus, dan Kapel Santo Petrus Kanisius di Kolese Kanisius.",
      ].join("\n\n"),
    },
    transits: [
      { kind: "bus", name: "Halte Pal Putih", line: "Koridor 5", distanceM: 200 },
    ],
    address: "Jalan Kramat Raya No. 134, RT.1/RW.9, Kramat, Senen, Jakarta Pusat, DKI Jakarta 10430",
    coords: [-6.186449, 106.844796],
  },
  {
    slug: "ekspatriat",
    name: { en: "St. Peter Canisius International Parish for Expatriates", id: "Paroki Internasional Santo Petrus Kanisius bagi Ekspatriat" },
    category: { en: "Personal Parish", id: "Paroki Personal" },
    parish: "Ekspatriat Parish",
    deanery: { en: "Central Jakarta", id: "Jakarta Pusat" },
    region: "Central Jakarta",
    group: ["menteng", "ekspatriat"],
    history: {
      en: [
        "Where every other parish in the Archdiocese is defined by territory, this one is defined by its people: a personal parish serving foreign Catholics living anywhere in Jakarta, regardless of which local parish they'd otherwise belong to. Fr. Mark Fortner, S.C.J. pioneered English-language Mass for the city's expatriate community, and the parish has operated formally since 2003 under the patronage of St. Peter Canisius, a Jesuit honored as a Doctor of the Church.",
        "Lacking a building of its own, it holds services across three sites: St. Theresa's Church in Menteng for Saturday and Sunday Mass, the chapel at Kolese Kanisius for Sunday evenings, and St. Stephen's Church in Cilandak on Tuesdays.",
      ].join("\n\n"),
      id: [
        "Berbeda dari paroki-paroki lain di KAJ yang bersifat teritorial, Paroki Ekspatriat merupakan paroki personal yang secara khusus melayani umat Katolik asing (ekspatriat) dari berbagai negara yang menetap di Jakarta, lintas batas wilayah paroki teritorial biasa. Perayaan Ekaristi berbahasa Inggris bagi kalangan ekspatriat dirintis oleh Pastor Mark Fortner, S.C.J., dan paroki ini resmi beroperasi sejak tahun 2003 di bawah pelindung Santo Petrus Kanisius, seorang Jesuit yang dikenal sebagai salah satu Pujangga Gereja.",
        "Karena tidak memiliki gedung gereja sendiri, kegiatan peribadatannya dilangsungkan di tiga lokasi: Gereja Santa Theresia, Menteng, sebagai tempat utama untuk misa Sabtu dan Minggu; Kapel Kolese Kanisius untuk misa Minggu sore; serta Gereja Santo Stefanus, Cilandak, untuk misa hari Selasa.",
      ].join("\n\n"),
    },
    transits: [],
    address: "-",
    coords: [-6.188889, 106.825472],
  },
  {
    slug: "blok-b",
    name: { en: "Gereja Santo Yohanes Penginjil", id: "Gereja Santo Yohanes Penginjil" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Blok B Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Melawai Raya No. 197, Jakarta Selatan 12130",
    coords: [-6.24552, 106.795318],
  },
  {
    slug: "blok-q",
    name: { en: "Gereja Santa Perawan Maria Ratu", id: "Gereja Santa Perawan Maria Ratu" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Blok Q Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Suryo No. 62, Rawa Barat, Kebayoran Baru, Jakarta Selatan 12180",
    coords: [-6.238404, 106.814513],
  },
  {
    slug: "cilandak",
    name: { en: "Gereja Santo Stefanus", id: "Gereja Santo Stefanus" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Cilandak Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan KH Muhasim Raya No. 2, Cilandak Barat, Jakarta Selatan 12430",
    coords: [-6.291139, 106.791215],
  },
  {
    slug: "jagakarsa",
    name: { en: "Gereja Ratu Rosari", id: "Gereja Ratu Rosari" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Jagakarsa Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Sirsak No. 14, RT 006/RW 07, Jagakarsa, Jakarta Selatan 12620",
    coords: [-6.339044, 106.827928],
  },
  {
    slug: "pasar-minggu",
    name: { en: "Gereja Keluarga Kudus", id: "Gereja Keluarga Kudus" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Pasar Minggu Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Pertanian III No. 26, Pasar Minggu, Jakarta Selatan 12520",
    coords: [-6.287825, 106.842968],
  },
  {
    slug: "tebet",
    name: { en: "Gereja Santo Fransiskus Asisi", id: "Gereja Santo Fransiskus Asisi" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Tebet Parish",
    deanery: { en: "South Jakarta", id: "Jakarta Selatan" },
    region: "South Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan KH Ramli No. 24, Menteng Dalam, Tebet, Jakarta Selatan 12870",
    coords: [-6.23136, 106.84161],
  },
  {
    slug: "cilincing",
    name: { en: "Gereja Salib Suci", id: "Gereja Salib Suci" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Cilincing Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Raya Tugu No. 12, RT 003/014, Semper, Koja, Jakarta Utara 14260",
    coords: [-6.125962, 106.919822],
  },
  {
    slug: "danau-sunter",
    name: { en: "Gereja Santo Yohanes Bosco", id: "Gereja Santo Yohanes Bosco" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Danau Sunter Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Taman Sunter Indah Blok A3/13-21, Sunter Jaya, Jakarta Utara 14350",
    coords: [-6.150861, 106.875082],
  },
  {
    slug: "kelapa-gading",
    name: { en: "Gereja Santo Yakobus", id: "Gereja Santo Yakobus" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Kelapa Gading Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Pulo Bira Besar, Kompleks TNI-AL Kodamar, Kelapa Gading Barat, Jakarta Utara 14240",
    coords: [-6.15722, 106.89361],
  },
  {
    slug: "pademangan",
    name: { en: "Gereja Santo Alfonsus Rodriguez", id: "Gereja Santo Alfonsus Rodriguez" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Pademangan Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Pademangan II Gang 7 No. 1, Jakarta Utara 14410",
    coords: [-6.141755, 106.842901],
  },
  {
    slug: "pantai-indah-kapuk",
    name: { en: "Gereja Regina Caeli", id: "Gereja Regina Caeli" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Pantai Indah Kapuk Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Mediterania Boulevard No. 1, Pantai Indah Kapuk, Kapuk Muara, Penjaringan, Jakarta Utara 14460",
    coords: [-6.110278, 106.765278],
  },
  {
    slug: "pluit",
    name: { en: "Gereja Stella Maris", id: "Gereja Stella Maris" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Pluit Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Taman Pluit Permai Timur No. 17, Pluit, Penjaringan, Jakarta Utara 14450",
    coords: [-6.112572, 106.791825],
  },
  {
    slug: "sunter",
    name: { en: "Gereja Santo Lukas", id: "Gereja Santo Lukas" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Sunter Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Ancol Selatan II RT 005/007 No. 8, Sunter Agung, Jakarta Utara 14350",
    coords: [-6.132253, 106.857433],
  },
  {
    slug: "tanjung-priok",
    name: { en: "Gereja Santo Fransiskus Xaverius", id: "Gereja Santo Fransiskus Xaverius" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Tanjung Priok Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Melati No. 1, Rawa Badak Utara, Koja, Jakarta Utara 14230",
    coords: [-6.115825, 106.893913],
  },
  {
    slug: "puspa-gading",
    name: { en: "Gereja Santo Andreas Kim Tae-gon", id: "Gereja Santo Andreas Kim Tae-gon" },
    category: { en: "Parish Church", id: "Gereja Paroki" },
    parish: "Puspa Gading Parish",
    deanery: { en: "North Jakarta", id: "Jakarta Utara" },
    region: "North Jakarta",
    history: { en: "Coming soon.", id: "Segera hadir." },
    transits: [],
    address: "Jalan Puspa Gading Timur Blok H2 No. 1, RT 005/RW 002, Pegangsaan Dua, Kelapa Gading, Jakarta Utara 14250",
    coords: [-6.173749, 106.91602],
  },
];

/** Chip order: "All" first, then regions in the order they appear in the data. */
export const regions = Array.from(new Set(churches.map((c) => c.region)));

export function getChurch(slug: string): Church | undefined {
  return churches.find((c) => c.slug === slug);
}
